export interface CountryData {
  id: string;
  name: string;
  capital: string;
  flag: string;
  language: string;
  description: string;
  currency?: string;
  history?: string;
  firstPresident?: string;
  independenceYear?: string;
}

export const africanCountries: CountryData[] = [
  {
    "id": "1",
    "name": "Algeria",
    "capital": "Algiers",
    "flag": "🇩🇿",
    "language": "Arabic / Berber",
    "description": "The largest country in Africa, located in the north.",
    "currency": "Algerian Dinar (DZD)",
    "firstPresident": "Ahmed Ben Bella",
    "independenceYear": "1962",
    "history": "Gained independence from France after a long and bloody war. It is rich in Roman history and natural gas."
  },
  {
    "id": "2",
    "name": "Angola",
    "capital": "Luanda",
    "flag": "🇦🇴",
    "language": "Portuguese",
    "description": "Known for its oil and mineral wealth in southern Africa.",
    "currency": "Angolan Kwanza (AOA)",
    "firstPresident": "Agostinho Neto",
    "independenceYear": "1975",
    "history": "Gained independence from Portugal, followed by a 27-year civil war. It has since become a major oil producer."
  },
  {
    "id": "3",
    "name": "Benin",
    "capital": "Porto-Novo",
    "flag": "🇧🇯",
    "language": "French",
    "description": "A small West African nation, the birthplace of Voodoo.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Hubert Maga",
    "independenceYear": "1960",
    "history": "Formerly Dahomey, it gained independence from France. It was a major center of the Atlantic slave trade and is the birthplace of Voodoo."
  },
  {
    "id": "4",
    "name": "Botswana",
    "capital": "Gaborone",
    "flag": "🇧🇼",
    "language": "English / Tswana",
    "description": "One of the most peaceful and stable countries in Africa.",
    "currency": "Botswana Pula (BWP)",
    "firstPresident": "Seretse Khama",
    "independenceYear": "1966",
    "history": "Formerly the British protectorate of Bechuanaland. It is known for its stable democracy and diamond wealth."
  },
  {
    "id": "5",
    "name": "Burkina Faso",
    "capital": "Ouagadougou",
    "flag": "🇧🇫",
    "language": "French",
    "description": "Means 'Land of the Honest Men'.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Maurice Yaméogo",
    "independenceYear": "1960",
    "history": "Formerly Upper Volta, gained independence from France. Thomas Sankara famously renamed it Burkina Faso in 1984."
  },
  {
    "id": "6",
    "name": "Burundi",
    "capital": "Gitega",
    "flag": "🇧🇮",
    "language": "Kirundi / French",
    "description": "A small mountainous nation in East Africa.",
    "currency": "Burundian Franc (BIF)",
    "firstPresident": "Michel Micombero",
    "independenceYear": "1962",
    "history": "Gained independence from Belgium as a monarchy, overthrown in 1966. Its history has been marked by ethnic tensions."
  },
  {
    "id": "7",
    "name": "Cabo Verde",
    "capital": "Praia",
    "flag": "🇨🇻",
    "language": "Portuguese",
    "description": "An archipelago located in the Atlantic Ocean.",
    "currency": "Cape Verdean Escudo (CVE)",
    "firstPresident": "Aristides Pereira",
    "independenceYear": "1975",
    "history": "Gained independence from Portugal. It is known for its stable democracy and Creole culture."
  },
  {
    "id": "8",
    "name": "Cameroon",
    "capital": "Yaoundé",
    "flag": "🇨🇲",
    "language": "French / English",
    "description": "Known as 'Africa in miniature' for its geological diversity.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "Ahmadou Ahidjo",
    "independenceYear": "1960",
    "history": "Formed by the merging of French and British Cameroons. It is known as 'Africa in miniature'."
  },
  {
    "id": "9",
    "name": "Central African Republic",
    "capital": "Bangui",
    "flag": "🇨🇫",
    "language": "Sango / French",
    "description": "A landlocked nation in Central Africa.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "David Dacko",
    "independenceYear": "1960",
    "history": "Gained independence from France. It has experienced significant political instability."
  },
  {
    "id": "10",
    "name": "Chad",
    "capital": "N'Djamena",
    "flag": "🇹🇩",
    "language": "Arabic / French",
    "description": "Named after Lake Chad, a large landlocked country.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "François Tombalbaye",
    "independenceYear": "1960",
    "history": "Gained independence from France. It has suffered from civil wars and conflicts with Libya."
  },
  {
    "id": "11",
    "name": "Comoros",
    "capital": "Moroni",
    "flag": "🇰🇲",
    "language": "Comorian / Arabic / French",
    "description": "A volcanic archipelago in the Indian Ocean.",
    "currency": "Comorian Franc (KMF)",
    "firstPresident": "Ahmed Abdallah",
    "independenceYear": "1975",
    "history": "Gained independence from France, though Mayotte voted to remain French. It has seen numerous coups."
  },
  {
    "id": "12",
    "name": "DR Congo",
    "capital": "Kinshasa",
    "flag": "🇨🇩",
    "language": "French / Lingala / Swahili",
    "description": "A vast country with immense natural resources.",
    "currency": "Congolese Franc (CDF)",
    "firstPresident": "Joseph Kasa-Vubu",
    "independenceYear": "1960",
    "history": "Gained independence from Belgium. It has faced massive conflicts despite immense mineral wealth."
  },
  {
    "id": "13",
    "name": "Republic of the Congo",
    "capital": "Brazzaville",
    "flag": "🇨🇬",
    "language": "French / Lingala / Kikongo",
    "description": "Located on the western side of the Congo River.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "Fulbert Youlou",
    "independenceYear": "1960",
    "history": "Gained independence from France. It had a long period of Marxist-Leninist rule."
  },
  {
    "id": "14",
    "name": "Djibouti",
    "capital": "Djibouti",
    "flag": "🇩🇯",
    "language": "French / Arabic",
    "description": "Strategically located in the Horn of Africa.",
    "currency": "Djiboutian Franc (DJF)",
    "firstPresident": "Hassan Gouled Aptidon",
    "independenceYear": "1977",
    "history": "Gained independence from France. It hosts several international military bases due to its strategic location."
  },
  {
    "id": "15",
    "name": "Egypt",
    "capital": "Cairo",
    "flag": "🇪🇬",
    "language": "Arabic",
    "description": "Home to the ancient pyramids and the Nile River.",
    "currency": "Egyptian Pound (EGP)",
    "firstPresident": "Muhammad Naguib",
    "independenceYear": "1922",
    "history": "One of the world's oldest continuous civilizations. Modern Egypt became a republic in 1953."
  },
  {
    "id": "16",
    "name": "Equatorial Guinea",
    "capital": "Malabo",
    "flag": "🇬🇶",
    "language": "Spanish / French / Portuguese",
    "description": "The only African country with Spanish as an official language.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "Francisco Macías Nguema",
    "independenceYear": "1968",
    "history": "Gained independence from Spain. It is now a major oil producer."
  },
  {
    "id": "17",
    "name": "Eritrea",
    "capital": "Asmara",
    "flag": "🇪🇷",
    "language": "Tigrinya / Arabic / English",
    "description": "Located in the Horn of Africa along the Red Sea.",
    "currency": "Eritrean Nakfa (ERN)",
    "firstPresident": "Isaias Afwerki",
    "independenceYear": "1993",
    "history": "Gained independence from Ethiopia after a 30-year war."
  },
  {
    "id": "18",
    "name": "Eswatini",
    "capital": "Mbabane",
    "flag": "🇸🇿",
    "language": "Swati / English",
    "description": "One of the few remaining absolute monarchies.",
    "currency": "Swazi Lilangeni (SZL)",
    "firstPresident": "King Sobhuza II",
    "independenceYear": "1968",
    "history": "Gained independence from Britain. It is Africa's last absolute monarchy."
  },
  {
    "id": "19",
    "name": "Ethiopia",
    "capital": "Addis Ababa",
    "flag": "🇪🇹",
    "language": "Amharic",
    "description": "The only African country that was never colonized.",
    "currency": "Ethiopian Birr (ETB)",
    "firstPresident": "Mengistu Haile Mariam",
    "independenceYear": "Never Colonized",
    "history": "One of the oldest nations in the world and never fully colonized. The monarchy ended in 1974."
  },
  {
    "id": "20",
    "name": "Gabon",
    "capital": "Libreville",
    "flag": "🇬🇦",
    "language": "French",
    "description": "A nation with dense forests and a small population.",
    "currency": "Central African CFA franc (XAF)",
    "firstPresident": "Léon M'ba",
    "independenceYear": "1960",
    "history": "Gained independence from France. It is known for its dense rainforests and oil wealth."
  },
  {
    "id": "21",
    "name": "Gambia",
    "capital": "Banjul",
    "flag": "🇬🇲",
    "language": "English",
    "description": "The smallest country on mainland Africa.",
    "currency": "Gambian Dalasi (GMD)",
    "firstPresident": "Dawda Jawara",
    "independenceYear": "1965",
    "history": "Gained independence from Britain. It is the smallest country on mainland Africa."
  },
  {
    "id": "22",
    "name": "Ghana",
    "capital": "Accra",
    "flag": "🇬🇭",
    "language": "English",
    "description": "The first sub-Saharan nation to gain independence.",
    "currency": "Ghanaian Cedi (GHS)",
    "firstPresident": "Kwame Nkrumah",
    "independenceYear": "1957",
    "history": "The first sub-Saharan nation to gain independence from Britain."
  },
  {
    "id": "23",
    "name": "Guinea",
    "capital": "Conakry",
    "flag": "🇬🇳",
    "language": "French",
    "description": "Has immense bauxite mineral wealth.",
    "currency": "Guinean Franc (GNF)",
    "firstPresident": "Ahmed Sékou Touré",
    "independenceYear": "1958",
    "history": "Gained independence from France after rejecting the French Community."
  },
  {
    "id": "24",
    "name": "Guinea-Bissau",
    "capital": "Bissau",
    "flag": "🇬🇼",
    "language": "Portuguese",
    "description": "A small West African country known for its national parks.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Luís Cabral",
    "independenceYear": "1973",
    "history": "Declared independence from Portugal after a guerrilla war."
  },
  {
    "id": "25",
    "name": "Ivory Coast",
    "capital": "Yamoussoukro",
    "flag": "🇨🇮",
    "language": "French",
    "description": "The world's leading producer of cocoa.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Félix Houphouët-Boigny",
    "independenceYear": "1960",
    "history": "Gained independence from France and became a top cocoa producer."
  },
  {
    "id": "26",
    "name": "Kenya",
    "capital": "Nairobi",
    "flag": "🇰🇪",
    "language": "Swahili / English",
    "description": "A major economic and cultural hub in East Africa.",
    "currency": "Kenyan Shilling (KES)",
    "firstPresident": "Jomo Kenyatta",
    "independenceYear": "1963",
    "history": "Gained independence from Britain following the Mau Mau rebellion."
  },
  {
    "id": "27",
    "name": "Lesotho",
    "capital": "Maseru",
    "flag": "🇱🇸",
    "language": "Sesotho / English",
    "description": "A country completely surrounded by South Africa.",
    "currency": "Lesotho Loti (LSL)",
    "firstPresident": "King Moshoeshoe II",
    "independenceYear": "1966",
    "history": "Gained independence from Britain. It is completely surrounded by South Africa."
  },
  {
    "id": "28",
    "name": "Liberia",
    "capital": "Monrovia",
    "flag": "🇱🇷",
    "language": "English",
    "description": "Founded by freed African-American citizens.",
    "currency": "Liberian Dollar (LRD)",
    "firstPresident": "Joseph Jenkins Roberts",
    "independenceYear": "1847",
    "history": "Founded by freed American slaves in 1822 and declared independence in 1847."
  },
  {
    "id": "29",
    "name": "Libya",
    "capital": "Tripoli",
    "flag": "🇱🇾",
    "language": "Arabic",
    "description": "A North African nation largely covered by desert.",
    "currency": "Libyan Dinar (LYD)",
    "firstPresident": "King Idris",
    "independenceYear": "1951",
    "history": "Gained independence as a kingdom. Muammar Gaddafi ruled from 1969 to 2011."
  },
  {
    "id": "30",
    "name": "Madagascar",
    "capital": "Antananarivo",
    "flag": "🇲🇬",
    "language": "Malagasy / French",
    "description": "The world's fourth-largest island with unique biodiversity.",
    "currency": "Malagasy Ariary (MGA)",
    "firstPresident": "Philibert Tsiranana",
    "independenceYear": "1960",
    "history": "Gained independence from France. Known for its unique flora and fauna."
  },
  {
    "id": "31",
    "name": "Malawi",
    "capital": "Lilongwe",
    "flag": "🇲🇼",
    "language": "Chichewa / English",
    "description": "Known as the 'Warm Heart of Africa'.",
    "currency": "Malawian Kwacha (MWK)",
    "firstPresident": "Hastings Banda",
    "independenceYear": "1964",
    "history": "Gained independence from Britain."
  },
  {
    "id": "32",
    "name": "Mali",
    "capital": "Bamako",
    "flag": "🇲🇱",
    "language": "French / Bambara",
    "description": "Once the center of a great West African empire.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Modibo Keïta",
    "independenceYear": "1960",
    "history": "Once the center of the Mali Empire. Gained independence from France."
  },
  {
    "id": "33",
    "name": "Mauritania",
    "capital": "Nouakchott",
    "flag": "🇲🇷",
    "language": "Arabic",
    "description": "Bridges the Maghreb and the Sahel regions.",
    "currency": "Mauritanian Ouguiya (MRU)",
    "firstPresident": "Moktar Ould Daddah",
    "independenceYear": "1960",
    "history": "Gained independence from France. Bridges Arab North Africa and Sub-Saharan Africa."
  },
  {
    "id": "34",
    "name": "Mauritius",
    "capital": "Port Louis",
    "flag": "🇲🇺",
    "language": "English / French / Creole",
    "description": "A beautiful island nation in the Indian Ocean.",
    "currency": "Mauritian Rupee (MUR)",
    "firstPresident": "Sir Seewoosagur Ramgoolam",
    "independenceYear": "1968",
    "history": "Gained independence from Britain. It is a highly developed island nation."
  },
  {
    "id": "35",
    "name": "Morocco",
    "capital": "Rabat",
    "flag": "🇲🇦",
    "language": "Arabic / Berber",
    "description": "A North African country with a rich mix of cultures.",
    "currency": "Moroccan Dirham (MAD)",
    "firstPresident": "King Mohammed V",
    "independenceYear": "1956",
    "history": "Gained independence from France and Spain. It has a rich history spanning Islamic dynasties."
  },
  {
    "id": "36",
    "name": "Mozambique",
    "capital": "Maputo",
    "flag": "🇲🇿",
    "language": "Portuguese",
    "description": "Has a long and beautiful coastline along the Indian Ocean.",
    "currency": "Mozambican Metical (MZN)",
    "firstPresident": "Samora Machel",
    "independenceYear": "1975",
    "history": "Gained independence from Portugal, followed by a 15-year civil war."
  },
  {
    "id": "37",
    "name": "Namibia",
    "capital": "Windhoek",
    "flag": "🇳🇦",
    "language": "English",
    "description": "Famous for the Namib Desert meeting the ocean.",
    "currency": "Namibian Dollar (NAD)",
    "firstPresident": "Sam Nujoma",
    "independenceYear": "1990",
    "history": "Gained independence from South Africa after a long struggle."
  },
  {
    "id": "38",
    "name": "Niger",
    "capital": "Niamey",
    "flag": "🇳🇪",
    "language": "French",
    "description": "Most of the country is covered by the Sahara Desert.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Hamani Diori",
    "independenceYear": "1960",
    "history": "Gained independence from France. Much of the country is in the Sahara desert."
  },
  {
    "id": "39",
    "name": "Nigeria",
    "capital": "Abuja",
    "flag": "🇳🇬",
    "language": "English",
    "description": "The most populous country in Africa.",
    "currency": "Nigerian Naira (NGN)",
    "firstPresident": "Nnamdi Azikiwe",
    "independenceYear": "1960",
    "history": "Gained independence from Britain. Experienced the Biafran Civil War from 1967-1970."
  },
  {
    "id": "40",
    "name": "Rwanda",
    "capital": "Kigali",
    "flag": "🇷🇼",
    "language": "Kinyarwanda / French / English",
    "description": "Known as the 'Land of a Thousand Hills'.",
    "currency": "Rwandan Franc (RWF)",
    "firstPresident": "Grégoire Kayibanda",
    "independenceYear": "1962",
    "history": "Gained independence from Belgium. The country experienced a tragic genocide in 1994."
  },
  {
    "id": "41",
    "name": "São Tomé and Príncipe",
    "capital": "São Tomé",
    "flag": "🇸🇹",
    "language": "Portuguese",
    "description": "A small island nation in Central Africa.",
    "currency": "São Tomé and Príncipe Dobra (STN)",
    "firstPresident": "Manuel Pinto da Costa",
    "independenceYear": "1975",
    "history": "Gained independence from Portugal."
  },
  {
    "id": "42",
    "name": "Senegal",
    "capital": "Dakar",
    "flag": "🇸🇳",
    "language": "French / Wolof",
    "description": "The gateway to West Africa.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Léopold Sédar Senghor",
    "independenceYear": "1960",
    "history": "Gained independence from France."
  },
  {
    "id": "43",
    "name": "Seychelles",
    "capital": "Victoria",
    "flag": "🇸🇨",
    "language": "Creole / English / French",
    "description": "An archipelago of paradise islands in the Indian Ocean.",
    "currency": "Seychellois Rupee (SCR)",
    "firstPresident": "James Mancham",
    "independenceYear": "1976",
    "history": "Gained independence from Britain. It is famous for luxury tourism."
  },
  {
    "id": "44",
    "name": "Sierra Leone",
    "capital": "Freetown",
    "flag": "🇸🇱",
    "language": "English / Krio",
    "description": "Famous for its white beaches and stunning scenery.",
    "currency": "Sierra Leonean Leone (SLL)",
    "firstPresident": "Milton Margai",
    "independenceYear": "1961",
    "history": "Gained independence from Britain. It suffered a devastating civil war in the 1990s."
  },
  {
    "id": "45",
    "name": "Somalia",
    "capital": "Mogadishu",
    "flag": "🇸🇴",
    "language": "Somali / Arabic",
    "description": "Has the longest coastline in mainland Africa.",
    "currency": "Somali Shilling (SOS)",
    "firstPresident": "Aden Abdullah Osman Daar",
    "independenceYear": "1960",
    "history": "Formed by the union of British and Italian Somaliland."
  },
  {
    "id": "46",
    "name": "South Africa",
    "capital": "Pretoria",
    "flag": "🇿🇦",
    "language": "11 Official Languages",
    "description": "Known as the 'Rainbow Nation'.",
    "currency": "South African Rand (ZAR)",
    "firstPresident": "Nelson Mandela",
    "independenceYear": "1910",
    "history": "Became a republic in 1961. The apartheid system ended in 1994 when Nelson Mandela became the first black president."
  },
  {
    "id": "47",
    "name": "South Sudan",
    "capital": "Juba",
    "flag": "🇸🇸",
    "language": "English",
    "description": "The world's newest nation, gained independence in 2011.",
    "currency": "South Sudanese Pound (SSP)",
    "firstPresident": "Salva Kiir Mayardit",
    "independenceYear": "2011",
    "history": "Gained independence from Sudan, making it the world's newest country."
  },
  {
    "id": "48",
    "name": "Sudan",
    "capital": "Khartoum",
    "flag": "🇸🇩",
    "language": "Arabic / English",
    "description": "Where the White Nile and Blue Nile meet.",
    "currency": "Sudanese Pound (SDG)",
    "firstPresident": "Ismail al-Azhari",
    "independenceYear": "1956",
    "history": "Gained independence from joint British-Egyptian rule."
  },
  {
    "id": "49",
    "name": "Tanzania",
    "capital": "Dodoma",
    "flag": "🇹🇿",
    "language": "Swahili / English",
    "description": "Home to Mount Kilimanjaro and the Serengeti.",
    "currency": "Tanzanian Shilling (TZS)",
    "firstPresident": "Julius Nyerere",
    "independenceYear": "1961",
    "history": "Formed in 1964 by the union of Tanganyika and Zanzibar."
  },
  {
    "id": "50",
    "name": "Togo",
    "capital": "Lomé",
    "flag": "🇹🇬",
    "language": "French",
    "description": "A small but elongated country in West Africa.",
    "currency": "West African CFA franc (XOF)",
    "firstPresident": "Sylvanus Olympio",
    "independenceYear": "1960",
    "history": "Gained independence from France."
  },
  {
    "id": "51",
    "name": "Tunisia",
    "capital": "Tunis",
    "flag": "🇹🇳",
    "language": "Arabic",
    "description": "A North African country bordering the Mediterranean Sea.",
    "currency": "Tunisian Dinar (TND)",
    "firstPresident": "Habib Bourguiba",
    "independenceYear": "1956",
    "history": "Gained independence from France. It was the birthplace of the Arab Spring in 2011."
  },
  {
    "id": "52",
    "name": "Uganda",
    "capital": "Kampala",
    "flag": "🇺🇬",
    "language": "English / Swahili",
    "description": "Winston Churchill called it the 'Pearl of Africa'.",
    "currency": "Ugandan Shilling (UGX)",
    "firstPresident": "Sir Edward Mutesa",
    "independenceYear": "1962",
    "history": "Gained independence from Britain. Known for the tumultuous rule of Idi Amin in the 1970s."
  },
  {
    "id": "53",
    "name": "Zambia",
    "capital": "Lusaka",
    "flag": "🇿🇲",
    "language": "English",
    "description": "Famous for the spectacular Victoria Falls.",
    "currency": "Zambian Kwacha (ZMW)",
    "firstPresident": "Kenneth Kaunda",
    "independenceYear": "1964",
    "history": "Formerly Northern Rhodesia, gained independence from Britain."
  },
  {
    "id": "54",
    "name": "Zimbabwe",
    "capital": "Harare",
    "flag": "🇿🇼",
    "language": "English / Shona",
    "description": "Also shares Victoria Falls and the Great Zimbabwe ruins.",
    "currency": "US Dollar / RTGS Dollar (ZWL)",
    "firstPresident": "Canaan Banana",
    "independenceYear": "1980",
    "history": "Formerly Rhodesia, gained independence after a bush war."
  }
];
