export interface CountryData {
  id: string;
  name: string;
  capital: string;
  flag: string;
  language: string;
  description: string;
}

export const africanCountries: CountryData[] = [
  { id: "1", name: "Algeria", capital: "Algiers", flag: "🇩🇿", language: "Arabic / Berber", description: "The largest country in Africa, located in the north." },
  { id: "2", name: "Angola", capital: "Luanda", flag: "🇦🇴", language: "Portuguese", description: "Known for its oil and mineral wealth in southern Africa." },
  { id: "3", name: "Benin", capital: "Porto-Novo", flag: "🇧🇯", language: "French", description: "A small West African nation, the birthplace of Voodoo." },
  { id: "4", name: "Botswana", capital: "Gaborone", flag: "🇧🇼", language: "English / Tswana", description: "One of the most peaceful and stable countries in Africa." },
  { id: "5", name: "Burkina Faso", capital: "Ouagadougou", flag: "🇧🇫", language: "French", description: "Means 'Land of the Honest Men'." },
  { id: "6", name: "Burundi", capital: "Gitega", flag: "🇧🇮", language: "Kirundi / French", description: "A small mountainous nation in East Africa." },
  { id: "7", name: "Cabo Verde", capital: "Praia", flag: "🇨🇻", language: "Portuguese", description: "An archipelago located in the Atlantic Ocean." },
  { id: "8", name: "Cameroon", capital: "Yaoundé", flag: "🇨🇲", language: "French / English", description: "Known as 'Africa in miniature' for its geological diversity." },
  { id: "9", name: "Central African Republic", capital: "Bangui", flag: "🇨🇫", language: "Sango / French", description: "A landlocked nation in Central Africa." },
  { id: "10", name: "Chad", capital: "N'Djamena", flag: "🇹🇩", language: "Arabic / French", description: "Named after Lake Chad, a large landlocked country." },
  { id: "11", name: "Comoros", capital: "Moroni", flag: "🇰🇲", language: "Comorian / Arabic / French", description: "A volcanic archipelago in the Indian Ocean." },
  { id: "12", name: "DR Congo", capital: "Kinshasa", flag: "🇨🇩", language: "French / Lingala / Swahili", description: "A vast country with immense natural resources." },
  { id: "13", name: "Republic of the Congo", capital: "Brazzaville", flag: "🇨🇬", language: "French / Lingala / Kikongo", description: "Located on the western side of the Congo River." },
  { id: "14", name: "Djibouti", capital: "Djibouti", flag: "🇩🇯", language: "French / Arabic", description: "Strategically located in the Horn of Africa." },
  { id: "15", name: "Egypt", capital: "Cairo", flag: "🇪🇬", language: "Arabic", description: "Home to the ancient pyramids and the Nile River." },
  { id: "16", name: "Equatorial Guinea", capital: "Malabo", flag: "🇬🇶", language: "Spanish / French / Portuguese", description: "The only African country with Spanish as an official language." },
  { id: "17", name: "Eritrea", capital: "Asmara", flag: "🇪🇷", language: "Tigrinya / Arabic / English", description: "Located in the Horn of Africa along the Red Sea." },
  { id: "18", name: "Eswatini", capital: "Mbabane", flag: "🇸🇿", language: "Swati / English", description: "One of the few remaining absolute monarchies." },
  { id: "19", name: "Ethiopia", capital: "Addis Ababa", flag: "🇪🇹", language: "Amharic", description: "The only African country that was never colonized." },
  { id: "20", name: "Gabon", capital: "Libreville", flag: "🇬🇦", language: "French", description: "A nation with dense forests and a small population." },
  { id: "21", name: "Gambia", capital: "Banjul", flag: "🇬🇲", language: "English", description: "The smallest country on mainland Africa." },
  { id: "22", name: "Ghana", capital: "Accra", flag: "🇬🇭", language: "English", description: "The first sub-Saharan nation to gain independence." },
  { id: "23", name: "Guinea", capital: "Conakry", flag: "🇬🇳", language: "French", description: "Has immense bauxite mineral wealth." },
  { id: "24", name: "Guinea-Bissau", capital: "Bissau", flag: "🇬🇼", language: "Portuguese", description: "A small West African country known for its national parks." },
  { id: "25", name: "Ivory Coast", capital: "Yamoussoukro", flag: "🇨🇮", language: "French", description: "The world's leading producer of cocoa." },
  { id: "26", name: "Kenya", capital: "Nairobi", flag: "🇰🇪", language: "Swahili / English", description: "A major economic and cultural hub in East Africa." },
  { id: "27", name: "Lesotho", capital: "Maseru", flag: "🇱🇸", language: "Sesotho / English", description: "A country completely surrounded by South Africa." },
  { id: "28", name: "Liberia", capital: "Monrovia", flag: "🇱🇷", language: "English", description: "Founded by freed African-American citizens." },
  { id: "29", name: "Libya", capital: "Tripoli", flag: "🇱🇾", language: "Arabic", description: "A North African nation largely covered by desert." },
  { id: "30", name: "Madagascar", capital: "Antananarivo", flag: "🇲🇬", language: "Malagasy / French", description: "The world's fourth-largest island with unique biodiversity." },
  { id: "31", name: "Malawi", capital: "Lilongwe", flag: "🇲🇼", language: "Chichewa / English", description: "Known as the 'Warm Heart of Africa'." },
  { id: "32", name: "Mali", capital: "Bamako", flag: "🇲🇱", language: "French / Bambara", description: "Once the center of a great West African empire." },
  { id: "33", name: "Mauritania", capital: "Nouakchott", flag: "🇲🇷", language: "Arabic", description: "Bridges the Maghreb and the Sahel regions." },
  { id: "34", name: "Mauritius", capital: "Port Louis", flag: "🇲🇺", language: "English / French / Creole", description: "A beautiful island nation in the Indian Ocean." },
  { id: "35", name: "Morocco", capital: "Rabat", flag: "🇲🇦", language: "Arabic / Berber", description: "A North African country with a rich mix of cultures." },
  { id: "36", name: "Mozambique", capital: "Maputo", flag: "🇲🇿", language: "Portuguese", description: "Has a long and beautiful coastline along the Indian Ocean." },
  { id: "37", name: "Namibia", capital: "Windhoek", flag: "🇳🇦", language: "English", description: "Famous for the Namib Desert meeting the ocean." },
  { id: "38", name: "Niger", capital: "Niamey", flag: "🇳🇪", language: "French", description: "Most of the country is covered by the Sahara Desert." },
  { id: "39", name: "Nigeria", capital: "Abuja", flag: "🇳🇬", language: "English", description: "The most populous country in Africa." },
  { id: "40", name: "Rwanda", capital: "Kigali", flag: "🇷🇼", language: "Kinyarwanda / French / English", description: "Known as the 'Land of a Thousand Hills'." },
  { id: "41", name: "São Tomé and Príncipe", capital: "São Tomé", flag: "🇸🇹", language: "Portuguese", description: "A small island nation in Central Africa." },
  { id: "42", name: "Senegal", capital: "Dakar", flag: "🇸🇳", language: "French / Wolof", description: "The gateway to West Africa." },
  { id: "43", name: "Seychelles", capital: "Victoria", flag: "🇸🇨", language: "Creole / English / French", description: "An archipelago of paradise islands in the Indian Ocean." },
  { id: "44", name: "Sierra Leone", capital: "Freetown", flag: "🇸🇱", language: "English / Krio", description: "Famous for its white beaches and stunning scenery." },
  { id: "45", name: "Somalia", capital: "Mogadishu", flag: "🇸🇴", language: "Somali / Arabic", description: "Has the longest coastline in mainland Africa." },
  { id: "46", name: "South Africa", capital: "Pretoria", flag: "🇿🇦", language: "11 Official Languages", description: "Known as the 'Rainbow Nation'." },
  { id: "47", name: "South Sudan", capital: "Juba", flag: "🇸🇸", language: "English", description: "The world's newest nation, gained independence in 2011." },
  { id: "48", name: "Sudan", capital: "Khartoum", flag: "🇸🇩", language: "Arabic / English", description: "Where the White Nile and Blue Nile meet." },
  { id: "49", name: "Tanzania", capital: "Dodoma", flag: "🇹🇿", language: "Swahili / English", description: "Home to Mount Kilimanjaro and the Serengeti." },
  { id: "50", name: "Togo", capital: "Lomé", flag: "🇹🇬", language: "French", description: "A small but elongated country in West Africa." },
  { id: "51", name: "Tunisia", capital: "Tunis", flag: "🇹🇳", language: "Arabic", description: "A North African country bordering the Mediterranean Sea." },
  { id: "52", name: "Uganda", capital: "Kampala", flag: "🇺🇬", language: "English / Swahili", description: "Winston Churchill called it the 'Pearl of Africa'." },
  { id: "53", name: "Zambia", capital: "Lusaka", flag: "🇿🇲", language: "English", description: "Famous for the spectacular Victoria Falls." },
  { id: "54", name: "Zimbabwe", capital: "Harare", flag: "🇿🇼", language: "English / Shona", description: "Also shares Victoria Falls and the Great Zimbabwe ruins." }
];
